// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:evently_1/models/task_model.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static CollectionReference<TaskModel> getTasksCollection() {
    // التأكد من أن الـ Firestore قد تم تهيئته
    final collection = FirebaseFirestore.instance.collection("Tasks");

    return collection.withConverter<TaskModel>(
      fromFirestore: (snapshot, options) {
        return TaskModel.fromJson(
          snapshot.data()!,
        ); // باستخدام ! لفرض أن البيانات موجودة
      },
      toFirestore: (value, options) {
        return value.toJson();
      },
    );
  }

  static Future<void> createTask(TaskModel task) {
    var collection = getTasksCollection();
    var doc = collection.doc();
    task.id = doc.id;
    return doc.set(task);
  }

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmlMEP9JV4kBSx_H01vnT5GGKZ7AsuRqo',
    appId: '1:887653112112:android:0a90f0050a418d1986d0f5',
    messagingSenderId: '887653112112',
    projectId: 'evently-7c804',
    storageBucket: 'evently-7c804.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqOLBv551QoPJgQyx3uG1fiQMvlHtiW_g',
    appId: '1:887653112112:ios:1f7a4360c086af2386d0f5',
    messagingSenderId: '887653112112',
    projectId: 'evently-7c804',
    storageBucket: 'evently-7c804.firebasestorage.app',
    iosBundleId: 'com.example.evently1',
  );
}
